application: balmy-moonlight-372
version: alpha-004
runtime: go
api_version: go1
beta_settings:
  cloud_sql_instances: ["balmy-moonlight-372:us-central1:galaga-sql-01"]
skip_files:
- ^_ignore$
- ^bower_components$

handlers:
- url: /
  script: index.go

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /images
  static_dir: images

- url: /ajax
  script: ajax.go

- url: /(.+)
  static_files: app/app/\1
  upload: .*
