application: balmy-moonlight-372
version: alpha-002
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /map
  static_dir: map

- url: /map
  static_files: map/map.html
  upload: map/map.html

- url: /.*
  script: _go_app
